[identity]
use = "identity"
aliases = ["id"]
hidden = true
short = "Reveal the creator god of the Kuba people"
long = """
Mbombo, also called Bumba, is the creator god in the religion
and mythology of the Kuba people of Central Africa in the area
that is now known as Democratic Republic of the Congo

In the Mbombo creation myth, Mbombo was a giant in form and
white in color. The myth describes the creation of the universe
from nothing
"""

[completion]
use = "completion [bash|zsh|fish|powershell]"
hidden = true
long = """
To load completions:

Bash:

  $ source <(%%[1]s completion bash)

  # To load completions for each session, execute once:
  # Linux:
  $ %%[1]s completion bash > /etc/bash_completion.d/%%[1]s
  # macOS:
  $ %%[1]s completion bash > $(brew --prefix)/etc/bash_completion.d/%%[1]s

Zsh:

  # If shell completion is not already enabled in your environment,
  # you will need to enable it. You can execute the following once:

  $ echo "autoload -U compinit; compinit" >> ~/.zshrc

  # To load completions for each session, execute once:
  $ %%[1]s completion zsh > "${fpath[1]}/_%%[1]s"

  # You will need to start a new shell for this setup to take effect.

fish:

  $ %%[1]s completion fish | source

  # To load completions for each session, execute once:
  $ %%[1]s completion fish > ~/.config/fish/completions/%%[1]s.fish

PowerShell:

  PS> %%[1]s completion powershell | Out-String | Invoke-Expression

  # To load completions for every new session, run:
  PS> %%[1]s completion powershell > %%[1]s.ps1
  # and source this file from your PowerShell profile.
"""
valid_args = ["bash", "zsh", "fish", "powershell"]

[forge]
use = "forge"
short = "Forge products"
long = "Forge by defining the materials, the destination & indicate pieces to replace"
example_usages = [["forge", "--help"]]

[root]
use = "mbombo"
long = "Forge a unifed product"
example_usages = [["help"]]
